name: Deploy Quarto site to Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Quarto
        run: |
          wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.deb
          sudo dpkg -i quarto-1.4.549-linux-amd64.deb
          quarto --version

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/quarto
          key: ${{ runner.os }}-quarto-${{ hashFiles('**/*.qmd', '**/*.yml', '**/*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-quarto-

      - name: Build
        run: quarto render

      - name: Setup redirects
        run: bash copy-redirects.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 